services:
  - type: web
    name: psr-tracker
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: AZURE_SENDER_EMAIL
        sync: false
